Disable BrowserStack log uploading
This causes the BrowserStack action to attempt to upload log files as
Github artefacts, and this has started failing for reasons I don't
understand.

Given that I didn't know it did this and that, to the best of my
knowledge, no one has ever looked at one of these files I think it's
fair to say that they are not providing a great deal of value.  So I'm
disabling it to hopefully make the problem go away.

Error messages looks like:

    Stopping local tunnel with local-identifier=GitHubAction-6090e27b-5bef-4bbf-9890-dac58b986689 in daemon mode...
    /opt/hostedtoolcache/BrowserStackLocal/1.0.0/x64/BrowserStackLocal --key *** --only-automate --ci-plugin GitHubAction --local-identifier GitHubAction-6090e27b-5bef-4bbf-9890-dac58b986689 --daemon stop
    {"status":"success","message":"BrowserStackLocal stopped successfully"}
    Local tunnel stopping status: BrowserStackLocal stopped successfully
    ##### Begin Diagnostic HTTP information #####
    Status Code: 400
    Status Message: Bad Request
    Header Information: {
      "content-length": "268",
      "content-type": "application/json; charset=utf-8",
      "date": "Thu, 30 Jan 2025 20:08:25 GMT",
      "server": "Kestrel",
      "cache-control": "no-store,no-cache",
      "pragma": "no-cache",
      "strict-transport-security": "max-age=2592000",
      "x-tfs-processid": "***",
      "activityid": "***",
      "x-tfs-session": "***",
      "x-vss-e2eid": "***",
      "x-vss-senderdeploymentid": "***",
      "x-frame-options": "SAMEORIGIN"
    }
    ###### End Diagnostic HTTP information ######
    Error: Action Failed: Error: Unable to create a container for the artifact BrowserStackLocal_functional_tests_1738267289541.log at https://pipelinesghubeus23.actions.githubusercontent.com/2GLhuSH0a3khSN9gDY9byjxJnQXzYeXYf4XP3OsMvzLqbDXg67/_apis/pipelines/workflows/13058688370/artifacts?api-version=6.0-previewocal-logging-level: all-logs